In [1]:
import numpy as np
import pandas as pd
import math
import os


In [2]:
df = pd.read_csv("data/data_train.csv")


In [3]:
print(df)

                   Id  Prediction
0              r44_c1           4
1              r61_c1           3
2              r67_c1           4
3              r72_c1           3
4              r86_c1           5
...               ...         ...
1176947   r9990_c1000           4
1176948   r9992_c1000           5
1176949   r9994_c1000           3
1176950   r9997_c1000           4
1176951  r10000_c1000           3

[1176952 rows x 2 columns]


In [13]:
def extract_users_items_predictions(data_pd):
    users, movies = \
        [np.squeeze(arr) for arr in np.split(data_pd.Id.str.extract('r(\d+)_c(\d+)').values.astype(int) - 1, 2, axis=-1)]
    predictions = data_pd.Prediction.values
    return users, movies, predictions

def create_data_matrix(users, movies, predictions, num_users=10000, num_movies=1000):
    #TODO: is float16 enough?
    matrix = np.zeros((num_users, num_movies), dtype=np.float16)
    matrix[users, movies] = predictions.astype(np.float16)
    return matrix

In [14]:
users, movies, predictions = extract_users_items_predictions(df)
matrix = create_data_matrix(users, movies, predictions)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 5. 3. 3.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 3.]]
